dist: trusty
language: python

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libboost-all-dev

install:
  - export ROOT_DIR=$PWD
  - wget https://dakota.sandia.gov/sites/default/files/distributions/public/dakota-6.6-public.src.tar.gz
  - tar zxf dakota-6.6-public.src.tar.gz
  - cd dakota-6.6.0.src/
  - mkdir build
  - cd build
  - cmake -DDAKOTA_HAVE_MPI=FALSE ..
  - make -j 3

script:
  - cd $ROOT_DIR
  - # python -m unittest discover tests
