dist: trusty
language: python

addons:
  apt:
    sources:
      - sourceline: 'ppa:jokva/carolina'
    packages:
      - dakota1
      - libdakota-dev
      - libboost-python-dev
      - libboost-all-dev

script:
  - python setup.py build
  - export PYTHONPATH=$PYTHONPATH:$PWD/build/lib.linux-x86_64-2.7
  - python -m unittest discover tests
